### ISSUE TITLE
Can't find the CORS settings in Revel

### ISSUE THREAD

**Issue by stagfoo** [RevelSystems/Online-Ordering#1]
Hey Guys,
is this location still correct `Settings->Online Ordering` ? I looked everywhere and couldn't find it.

**Comment by evegorov** [comment]
The option should be: https://<server-domain-name>/settings/advanced/online_ordering/  > select "Online Ordering Settings" tab in the left side menu > find "CORS Allowed Origins" input field (it's placed at the bottom of the settings page).

**Comment by stagfoo** [comment]
awesome all working now
