### ISSUE TITLE
Default location selection

### ISSUE THREAD

**Issue by xmrtni** [RevelSystems/Online-Ordering#13]
Hello, can you tell me where/how the default location is selected when the app loads? Right now it defaults to establishment 1 until the location is changed. I'm trying to default to either the location closest to the user or force them to choose a location.

Thank you

**Comment by mseimys** [comment]
Hey @xmrtni, I believe some of the lines along the
https://github.com/RevelSystems/Online-Ordering/blob/master/js/app.js#L378
handle the establishment loading and selection. Hope that helps!
