### ISSUE TITLE
API Options?

### ISSUE THREAD

**Issue by stagfoo** [RevelSystems/Online-Ordering#2]
Hey guys,
i have the setup working but i was wondering if there is any like restful api option that i can call out side of the application like
`/weborders/system_settings?establishment=1`

I want to have a featured product section outside of the shop section and i wanted to also have an persistent cart?

**Comment by apakhunov** [comment]
Hi Alex,

Please contact David Grant <david@revelsystems.com> and Joe Wilson <joe.wilson@revelsystems.com>. They are handling Revel API support.

Best Regards,
Alex

**Comment by stagfoo** [comment]
Thanks Alex
